apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom: 
              secretKeyRef: 
                name: mongosecret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: mongosecret
                key: MONGO_INITDB_ROOT_PASSWORD
     
        volumeMounts: 
          - name: mongopv
            mountPath: /data/db
          - name: mongo-ssl-volume
            mountPath: /etc/ssl/mongo
            readOnly: true

      volumes:
        - name: mongo-ssl-volume
          secret:
            secretName: mongo-ssl
        - name: mongopv
          persistentVolumeClaim: 
            claimName: mypvc2
